---
- name: Get bridge repo
  git:
    repo: "{{ bridge_repo }}"
    dest: "{{ bridge_path }}"
    force: no
    update: no
    refspec: "{{ bridge_repo_branch }}"
    version: "{{ bridge_repo_branch }}"
- name: Initialize submodules
  shell: git submodule update --init
  args:
    chdir: "{{ bridge_path }}"
