---
driver:
  name: docker
platforms:
  - name: all-host
    groups:
      - example
    children:
      - oracle
      - ui
      - monitor
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../../../deployment/site.yml
  inventory:
    host_vars:
      all-host:
        VALIDATOR_ADDRESS_PRIVATE_KEY: "8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9"
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  lint:
    name: flake8
  additional_files_or_dirs:
    - ../../tests/*
    - ../../oracle/tests/*
    - ../../ui/tests/*
    - ../../monitor/tests/*
scenario:
  name: all
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
